### ISSUE TITLE
Error: Cannot read property 'login' of null

### ISSUE THREAD

**Issue by AF250329** [johnyherangi/release-notes#145]
Hi

Suddenly your action started to fail with error message `Error: Cannot read property 'login' of null` 

![image](https://user-images.githubusercontent.com/78792938/136685277-751b4873-c0e3-4a8d-b1d2-46f51ce71df1.png)

I mean - it was working before and I sucsesfully made a couple releases but suddenly it start to throw errors

P.S. I do start the workflow from `Run workflow` button and not from `on push` event if it relevant....

**Comment by Devofure** [comment]
I get the same problem now, it does not work anymore 😞

**Comment by peterdobrosi-seon** [comment]
Same for me :(

**Comment by Devofure** [comment]
@johnyherangi could you help us fix that issue?

**Comment by johnyherangi** [comment]
Hey all, apologies for not seeing this sooner. I may need to update my notification settings 😖 

I have a fix but I don't have a branch that can reproduce this issue in order to test. If someone can confirm the action is working for them using the version below I will merge and update the `v1` tag.

```sh
- uses: johnyherangi/create-release-notes@fix/handle-missing-commit-author
```

**Comment by Devofure** [comment]
I think it is working, I haven't seen this problem again, thank you!!
